name: Queries by Statement Type
description: "Shows the count of queries split by different statement types in Snowflake. "
tableName: snowflake_query_history
updatedAt: "2025-01-01T00:00:00.000Z"
metricQuery:
  exploreName: snowflake_query_history
  dimensions:
    - snowflake_query_history_query_type
  metrics:
    - snowflake_query_history_query_id_count_distinct_of_query_id
  filters: {}
  sorts:
    - fieldId: snowflake_query_history_query_type
      descending: false
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics:
    - name: query_id_count_distinct_of_query_id
      label: Count distinct of Query id
      description: "Count distinct of Query id on the table Snowflake query history "
      sql: ${TABLE}.query_id
      table: snowflake_query_history
      type: count_distinct
      baseDimensionName: query_id
      formatOptions:
        type: default
        separator: default
  customDimensions: []
chartConfig:
  type: pie
  config:
    isDonut: true
    metricId: snowflake_query_history_query_id_count_distinct_of_query_id
    showValue: false
    showLegend: true
    valueLabel: hidden
    groupFieldIds:
      - snowflake_query_history_query_type
    legendPosition: horizontal
    showPercentage: true
    groupSortOverrides: []
    groupColorOverrides: {}
    groupLabelOverrides: {}
    legendMaxItemLength: 30
    groupValueOptionOverrides: {}
dashboardSlug: ld-sf-snowflake-usage-tracking
spaceSlug: templates
slug: ld-sf-queries-by-statement-type
tableConfig:
  columnOrder:
    - snowflake_query_history_query_type
    - snowflake_query_history_query_id_count_distinct_of_query_id
version: 1
